# Generated by Django 2.2 on 2021-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问卷标题')),
                ('choice_one', models.CharField(max_length=255, verbose_name='默认选择1')),
                ('choice_two', models.CharField(max_length=255, verbose_name='默认选择2')),
                ('choice_three', models.CharField(max_length=255, verbose_name='默认选择3')),
                ('choice_four', models.CharField(max_length=255, verbose_name='默认选择4')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '调查问卷',
                'verbose_name_plural': '调查问卷',
                'ordering': ['-id'],
            },
        ),
    ]
